server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/amaristest
    username: esteban
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.pragma.powerup.infrastructure.out.feign.users.adapter: DEBUG